# Generated by Django 2.0.4 on 2018-04-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
