# Generated by Django 2.0.4 on 2018-04-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_brands',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_types',
        ),
        migrations.AddField(
            model_name='food',
            name='brands',
            field=models.ManyToManyField(to='food.Brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='food',
            name='types',
            field=models.ManyToManyField(to='food.Type', verbose_name='Type'),
        ),
    ]
