# Generated by Django 2.0.4 on 2018-04-15 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20180413_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
