# Generated by Django 2.0.4 on 2018-04-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20180415_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
